SRCS_CXX = LogUtility.cpp \
           GeneralTimer.cpp \
           SQLiteTable.cpp \
           SingleRowTable.cpp \
           MultiRowWithUniqueIndexTable.cpp \
           ConcreteTableBase.cpp \
           LargeTableBase.cpp

HEADS = Utility.h \
        SQLiteTable.h \
        TableNameDef.h \
        SingleRowTable.h \
        MultiRowWithUniqueIndexTable.h \
        LogUtility.h \
        LargeTableBase.h \
        GeneralTimer.h \
        ConcreteTableBase.h


OBJS = LogUtility.o \
       GeneralTimer.o \
       SQLiteTable.o \
       SingleRowTable.o \
       MultiRowWithUniqueIndexTable.o


include ../rules.mk
