SRCS_CXX = LogUtility.cpp \
           GeneralTimer.cpp \
           SQLiteTable.cpp \
           SingleRowTable.cpp \
           ConcreteTableBase.cpp \
           StaticConfigtable.cpp \
           HTTPBody.cpp \
           ControlChannel.cpp

HEADS = Utility.h \
        SQLiteTable.h \
        SingleRowTable.h \
        LogUtility.h \
        GeneralTimer.h \
        ConcreteTableBase.h \
        StaticConfigTable.h \
        HTTPBody.h \
        ControlChannel.h


OBJS = LogUtility.o \
       GeneralTimer.o \
       SQLiteTable.o \
       SingleRowTable.o \
       ConcreteTableBase.o \
       StaticConfigtable.o \
       HTTPBody.o \
       ControlChannel.o


include ../rules.mk
