SRCS_CXX = LogUtility.cpp \
           GeneralTimer.cpp \
           SQLiteTable.cpp \
           SingleRowTable.cpp \
           ConcreteTableBase.cpp \
           StaticConfigTable.cpp \
           HTTPBody.cpp \
           ControlChannel.cpp \
           RunningConfigTable.cpp \
           WebServer.cpp \
           ScanRecord.cpp \
           MacRecord.cpp \
           DataChannel.cpp \
           CollectChannel.cpp \
           main.cpp

HEADS = Utility.h \
        SQLiteTable.h \
        SingleRowTable.h \
        LogUtility.h \
        GeneralTimer.h \
        ConcreteTableBase.h \
        StaticConfigTable.h \
        HTTPBody.h \
        ControlChannel.h \
        RunningConfigTable.h \
        WebServer.h \
        ScanRecord.h \
        DataChannel.h \
        CollectChannel.h \
        MacRecord.h

TARGET = new_project


include ../rules.mk
